
language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
# command to run tests
#env:
#  - PYTHONPATH="${PYTHONPATH}:/Calculator:/CsvReader:/Tests:/Operations:/Statistics:/"
script:
  - python -m  unittest discover -s  Tests

branches:
  only:
    - master
    - statisticalCalculator